---
# tasks file for nginx_install

- name: install nginx
  yum: name=nginx state=latest

- name: copy index.html 
  template:
         src: index.html
         dest: /usr/share/nginx/html
  notify: restart nginx

- name: enable the service
  service:
         name: nginx
         enabled: yes
         state: started

 
